from __future__ import annotations

import base64
import hashlib
import os
import sqlite3
import struct
import subprocess
import sys
from pathlib import Path

from Cryptodome.Cipher import AES

CHROME_PROFILE_DIR = Path(os.path.expanduser("~/.config/google-chrome/Profile 4"))
COOKIES_DB = CHROME_PROFILE_DIR / "Cookies"
OUTPUT_FILE = Path("/root/yt_cookies.txt")
SAFE_STORAGE_ATTR = ("application", "chrome")


def get_keyring_password() -> str:
    """Retrieve Chrome Safe Storage password from gnome-keyring."""
    result = subprocess.run(
        ["secret-tool", "lookup", *SAFE_STORAGE_ATTR],
        capture_output=True, text=True, timeout=10,
    )
    if result.returncode != 0:
        raise RuntimeError(f"secret-tool failed: {result.stderr.strip()}")
    return result.stdout.strip()


def derive_key(password: str) -> bytes:
    """Derive AES key via PBKDF2-SHA1 (Chrome's method)."""
    return hashlib.pbkdf2_hmac("sha1", password.encode("utf-8"), b"saltysalt", 1, dklen=16)


def decrypt_cookie(encrypted: bytes, key: bytes) -> str:
    """Decrypt a Chrome v11 cookie value."""
    if not encrypted or encrypted[0:3] != b"v11":
        return None

    payload = encrypted[3:]
    iv = b" " * 16
    cipher = AES.new(key, AES.MODE_CBC, iv=iv)
    decrypted = cipher.decrypt(payload)
    # Strip PKCS#7 padding
    pad_len = decrypted[-1]
    if pad_len > 16:
        return None
    decrypted = decrypted[:-pad_len]
    # Strip 32-byte hash prefix
    decrypted = decrypted[32:]
    return decrypted.decode("utf-8", errors="replace")


def write_netscape_cookie(cookies: list[tuple]) -> str:
    """Write cookies in Netscape HTTP Cookie File format (yt-dlp compatible)."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by refresh_cookies.py. Do not edit.",
        "",
    ]
    for host, path, secure, expires_utc, name, value in cookies:
        if not host:
            continue
        # Chrome stores '.'-prefixed domains; yt-dlp expects domain without leading dot
        domain = host.lstrip(".")
        secure_flag = "TRUE" if secure else "FALSE"
        http_only = "FALSE"  # yt-dlp doesn't care about httponly for the cookie file
        # domain flag: TRUE if host_key starts with '.' (domain cookie), FALSE otherwise
        domain_flag = "TRUE" if domain.startswith(".") else "FALSE"

        expires = int(expires_utc / 1_000_000) if expires_utc else 0
        if expires == 0:
            expires = 9999999999

        lines.append(f"{domain}\t{domain_flag}\t{path}\t{secure_flag}\t{expires}\t{name}\t{value}")

    return "\n".join(lines) + "\n"


def main() -> None:
    if not COOKIES_DB.exists():
        print(f"Chrome cookies DB not found: {COOKIES_DB}", file=sys.stderr)
        sys.exit(1)

    password = get_keyring_password()
    key = derive_key(password)

    conn = sqlite3.connect(f"file:{COOKIES_DB}?immutable=1", uri=True)
    conn.row_factory = sqlite3.Row
    cursor = conn.execute(
        "SELECT host_key, path, is_secure, expires_utc, name, encrypted_value "
        "FROM cookies WHERE encrypted_value IS NOT NULL"
    )

    cookies = []
    for row in cursor:
        val = decrypt_cookie(row["encrypted_value"], key)
        if val:
            cookies.append((
                row["host_key"],
                row["path"],
                bool(row["is_secure"]),
                row["expires_utc"],
                row["name"],
                val,
            ))

    conn.close()

    netscape = write_netscape_cookie(cookies)
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(netscape)
    print(f"Wrote {len(cookies)} cookies to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
